services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: fastdelivery-sql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  mongo:
    image: mongo:latest
    container_name: fastdelivery-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  sql_data:
  mongo_data: